version: '3.8'

services:
  order-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgreS123
    ports:
      - "5434:5434"
    command:
      - "postgres"
      - "-c"
      - "port=5434"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - shared_network

  order:
    build:
      context: ../../
      dockerfile: CsharpBeer/CsharpBeer.OrderService/Dockerfile
    depends_on:
      - order-db
    ports:
      - "8082:8080"
    networks:
      - shared_network

volumes:
  order_data:

networks:
  shared_network:
    external: true