version: '3.8'

services:
  order-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgreS123
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  order:
    build: .
    depends_on:
      - order-db
    ports:
      - "8082:8080"

volumes:
  order_data:
