version: '3.8'

services:
  auth-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - shared_network

  sso:
    build: .
    depends_on:
      - auth-db
    ports:
      - "44044:44044"
    networks:
      - shared_network

volumes:
  auth_data:

networks:
  shared_network:
    external: true