name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: remote ssh connect & build & deploy
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop	: true
        script: |
          cd beer-api-itmo/
          git pull
          docker-compose down
          docker-compose -f sso/docker-compose.yml -f go_beer_catalog/docker-compose.yml -f CsharpBeer/CsharpBeer.OrderService/docker-compose.yml up -d
